{% set version = "6.3.20220516.1731" %}
{% set git_commit = "3a0971f471bb62e91a77b7560d480c80e9020132" %}

package:
  name: mantidqt
  version: {{ version }}

source:
  url: https://github.com/mantidproject/mantid/archive/{{ git_commit }}.tar.gz
  sha256: f289470d0006f013d41d8c84f4210d91c1a7f2868e6f04ffa07fc288c9ac6930

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('mantidqt', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - ninja  # [unix]
    - cmake
    - git
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]

  host:
    - eigen
    - jemalloc  # [unix]
    - mantid {{ version }}
    - python
    - pyqt
    - qt {{ qt }}
    - qscintilla2
    - setuptools {{ setuptools }}
    - tbb-devel {{ tbb }}

  run:
    - matplotlib {{ matplotlib }}
    - toml
    - {{ pin_compatible("qscintilla2", max_pin="x.x") }}
    - qtpy
    - python
    
test:
  imports:
    - mantidqt
    - mantidqt.icons

about:
  home: https://github.com/mantidproject/mantid
  license: GPL-3.0-or-later
  summary: Mantid provides a framework that supports high-performance computing and visualisation of materials science data.

extra:
  recipe-maintainers:
    - StephenSmith25
    - Pasarus