{% set version = "6.4.20220720.1133" %}
{% set git_commit = "98fc2e0912d0f1c2211bf3348fb07ef18fc9708f" %}

package:
  name: mantidqt
  version: {{ version }}

source:
  url: https://github.com/mantidproject/mantid/archive/{{ git_commit }}.tar.gz
  sha256: b0cb1f35ec5d9d097a3093f1c91805cf159cf8a627aad7a0271791c969a87c97

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('mantidqt', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - ninja  # [unix]
    - cmake
    - git
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]

  host:
    - eigen
    - jemalloc  # [unix]
    - mantid {{ version }}
    - python
    - pyqt
    - qt {{ qt }}
    - qscintilla2
    - setuptools {{ setuptools }}
    - tbb-devel {{ tbb }}

  run:
    - matplotlib {{ matplotlib }}
    - toml
    - {{ pin_compatible("qscintilla2", max_pin="x.x") }}
    - qtpy
    - python
    
test:
  imports:
    - mantidqt
    - mantidqt.icons

about:
  home: https://github.com/mantidproject/mantid
  license: GPL-3.0-or-later
  summary: Mantid provides a framework that supports high-performance computing and visualisation of materials science data.

extra:
  recipe-maintainers:
    - StephenSmith25
    - Pasarus