{% set version = "6.2.20220204.1616" %}
{% set git_commit = "1d1461afa325355385e74fd08b5042b447cf2499" %}

package:
  name: mantidqt
  version: {{ version }}

source:
  url: https://github.com/mantidproject/mantid/archive/{{ git_commit }}.tar.gz
  sha256: ba81b922e48e579f740b7605b96327c811b62d0ba8c4170595b094fb4211ac34

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('mantidqt', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - ninja  # [unix]
    - cmake
    - git
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]

  host:
    - eigen
    - jemalloc  # [unix]
    - mantid {{ version }}
    - python
    - pyqt
    - qt 5.12.*
    - qscintilla2
    - setuptools 48.0.*
    - tbb-devel 2020.2.*

  run:
    - matplotlib-base
    - {{ pin_compatible("qscintilla2", max_pin="x.x") }}
    - qtpy
    - python
    
test:
  imports:
    - mantidqt
    - mantidqt.icons

about:
  home: https://github.com/mantidproject/mantid
  license: GPL-3.0-or-later
  summary: Mantid provides a framework that supports high-performance computing and visualisation of materials science data.

extra:
  recipe-maintainers:
    - StephenSmith25
    - Pasarus