{% set version = "6.4.20220711.1204" %}
{% set git_commit = "cd85d40f6ce466e6357f0672eb898f2c31c7b29d" %}

package:
  name: mantidworkbench
  version: {{ version }}

source:
  url: https://github.com/mantidproject/mantid/archive/{{ git_commit }}.tar.gz
  sha256: 257e7e51b27966f37a10f93da86d1ea6d0d255d0e04faee7cf9a9885c69009a0

build:
  number: 0
  entry_points:
    - workbench = workbench.app.main:main
  osx_is_app: true

requirements:
  build:
    - {{ compiler("cxx") }}
    - ninja  # [unix]
    - cmake
    - git
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
  host:
    - boost {{ boost }}
    - setuptools {{ setuptools }}
    - mantidqt {{ version }}
    - sphinx
    - sphinx_bootstrap_theme
    - python
  run:    
    - ipykernel {{ ipykernel }}
    - psutil
    - {{ pin_compatible("python", max_pin="x.x") }}
    - matplotlib {{ matplotlib }}
    - python.app  # [osx]
    - qtconsole
    - {{ pin_compatible("setuptools", max_pin="x.x") }}

test:
  imports:
    - workbench

about:
  home: https://github.com/mantidproject/mantid
  license: GPL-3.0-or-later
  summary: Mantid provides a framework that supports high-performance computing and visualisation of materials science data.

extra:
  recipe-maintainers:
    - StephenSmith25
    - Pasarus