{% set version = "6.2.20220126.1258" %}
{% set git_commit = "1be29b32dfb3f5fc9cffb18fd479f7751f374876" %}

package:
  name: mantidworkbench
  version: {{ version }}

source:
  url: https://github.com/mantidproject/mantid/archive/{{ git_commit }}.tar.gz
  sha256: 525eb97b06ffad3c0a2b679ad80cce9402189b726233af2e179119ee20630692

build:
  number: 0
  entry_points:
    - workbench = workbench.app.main:main
  osx_is_app: true

requirements:
  build:
    - {{ compiler("cxx") }}
    - ninja  # [unix]
    - cmake
    - git
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
  host:
    - boost {{ boost }}
    - setuptools 48.0.*
    - mantidqt {{ version }}
    - sphinx
    - sphinx_bootstrap_theme
    - python
  run:    
    - ipykernel <6
    - psutil
    - {{ pin_compatible("python", max_pin="x.x") }}
    - python.app  # [osx]
    - qtconsole
    - {{ pin_compatible("setuptools", max_pin="x.x") }}

test:
  imports:
    - workbench

about:
  home: https://github.com/mantidproject/mantid
  license: GPL-3.0-or-later
  summary: Mantid provides a framework that supports high-performance computing and visualisation of materials science data.

extra:
  recipe-maintainers:
    - StephenSmith25
    - Pasarus