{% set version = "6.2.20220128.1758" %}
{% set git_commit = "7b1a8f07744a0aa18d5019d85d02c51dc9a35122" %}

package:
  name: mantidworkbench
  version: {{ version }}

source:
  url: https://github.com/mantidproject/mantid/archive/{{ git_commit }}.tar.gz
  sha256: 2cb5862d30e107ae67a463d6fcb3b6d73653766bee68af4690586349bb5b7378

build:
  number: 0
  entry_points:
    - workbench = workbench.app.main:main
  osx_is_app: true

requirements:
  build:
    - {{ compiler("cxx") }}
    - ninja  # [unix]
    - cmake
    - git
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
  host:
    - boost {{ boost }}
    - setuptools 48.0.*
    - mantidqt {{ version }}
    - sphinx
    - sphinx_bootstrap_theme
    - python
  run:    
    - ipykernel <6
    - psutil
    - {{ pin_compatible("python", max_pin="x.x") }}
    - python.app  # [osx]
    - qtconsole
    - {{ pin_compatible("setuptools", max_pin="x.x") }}

test:
  imports:
    - workbench

about:
  home: https://github.com/mantidproject/mantid
  license: GPL-3.0-or-later
  summary: Mantid provides a framework that supports high-performance computing and visualisation of materials science data.

extra:
  recipe-maintainers:
    - StephenSmith25
    - Pasarus