{% set version = "6.4.20220721.1346" %}
{% set git_commit = "a75473f0dbc232967217bd9a3f921a4d06f06322" %}

package:
  name: mantidworkbench
  version: {{ version }}

source:
  url: https://github.com/mantidproject/mantid/archive/{{ git_commit }}.tar.gz
  sha256: 3a44480b6dd281a6d47703e7e0c62710eb316fb2bb3b658da77f1402fd5875a4

build:
  number: 0
  entry_points:
    - workbench = workbench.app.main:main
  osx_is_app: true

requirements:
  build:
    - {{ compiler("cxx") }}
    - ninja  # [unix]
    - cmake
    - git
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
  host:
    - boost {{ boost }}
    - setuptools {{ setuptools }}
    - mantidqt {{ version }}
    - sphinx
    - sphinx_bootstrap_theme
    - python
  run:    
    - ipykernel {{ ipykernel }}
    - psutil
    - {{ pin_compatible("python", max_pin="x.x") }}
    - matplotlib {{ matplotlib }}
    - python.app  # [osx]
    - qtconsole
    - {{ pin_compatible("setuptools", max_pin="x.x") }}

test:
  imports:
    - workbench

about:
  home: https://github.com/mantidproject/mantid
  license: GPL-3.0-or-later
  summary: Mantid provides a framework that supports high-performance computing and visualisation of materials science data.

extra:
  recipe-maintainers:
    - StephenSmith25
    - Pasarus